In [2]:
import pandas as pd
import numpy as np

num_cols_=['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']



df_ori = pd.read_csv("D:\SummerResearch\data\\adult\onehot_adult_train.csv")
df_syn = pd.read_csv("D:\SummerResearch\data\\adult\onehot_adult_sdv_gaussian_100k.csv")

X_ori = df_ori.drop(columns=['income'])
X_syn = df_syn.drop(columns=['income'])
y_ori = df_ori['income']

print(df_ori.shape)
print(df_syn.shape)
# df_ori = df_ori.drop(columns=['Unnamed: 0'])
# df_syn = df_syn.drop(columns=['Unnamed: 0'])

(38095, 109)
(100000, 109)


In [3]:
from pca_gmm import PCA_GMM

model = PCA_GMM(X_original=X_ori, y_original=y_ori, X_synthesized=X_syn,
                 numerical_cols=num_cols_, target_name='income',
                 pca_n_components=0.99, gmm_n_components=10, verbose=True,
                 filename='draft.csv')

(train_acc, f1), synthesized_df= model.fit()

Normalizing data...


Before PCA: NaN values in data:  age                               0
fnlwgt                            0
capital-loss                      0
hours-per-week                    0
education-num                     0
                                 ..
native-country_Thailand           0
native-country_Trinadad&Tobago    0
native-country_United-States      0
native-country_Vietnam            0
native-country_Yugoslavia         0
Length: 108, dtype: int64
Performing PCA...
Assumes the dfs only contain numerical columns.
Explained variance ratio: [0.35583463 0.30387462 0.15151999 0.08577014 0.05218839 0.05081223]
Cumulative explained variance: [0.35583463 0.65970925 0.81122924 0.89699938 0.94918777 1.        ]
Number of components: 6


 pre df
<class 'numpy.ndarray'>
[[ 0.01284971  0.16815559 -0.14652938 -0.02174271 -0.00983636  0.01476393]
 [ 0.20785906 -0.18269455  0.01689317  0.35664398  0.03393765 -0.00105004]
 [ 0.16168925 -0.13503996 -0.05780776 -0.01922565 -0.032

pca_n_components=0.99, gmm_n_components=5

Train Accuracy:  0.8345452159075994

Train F1 {'weighted': 0.8321556339645861, 'macro': 0.7683326637288124, 'micro': 0.8345452159075994}

In [7]:
print(synthesized_df.head())
synthesized_df['capital-loss'].unique()

   age  capital-gain  capital-loss  education-num  education_10th  \
0   26             6             1              7             0.0   
1   45             1             0              1             0.0   
2   36             0             1             14             0.0   
3   61             0             0             14             0.0   
4   43             5             1             10             0.0   

   education_11th  education_12th  education_1st-4th  education_5th-6th  \
0             1.0             0.0                0.0                0.0   
1             0.0             0.0                1.0                0.0   
2             0.0             0.0                0.0                0.0   
3             0.0             0.0                0.0                0.0   
4             0.0             0.0                0.0                0.0   

   education_7th-8th  ...  workclass_?  workclass_Federal-gov  \
0                0.0  ...          0.0                    0.0   
1   

array([   1,    0,    2, 1881, 1839, 2171, 2125, 2085, 1853, 1801, 2207,
       2192, 2030, 1899, 1862, 2078, 1870, 2053, 1846, 1866, 1884, 1972,
       1821, 1786, 1799, 1837, 1817, 1857, 1887, 1874, 1852, 1849, 1918,
       1851, 2105, 2228, 1893, 2088, 1989, 1825, 1822, 1769, 2124, 1886,
       1871, 1826, 2160, 1803, 1831, 1812, 1894, 1875, 2002, 1844, 1867,
       1835, 1790, 1815, 1898, 1904, 1889, 1777, 2126, 2256, 1832, 1792,
       1768, 1914, 1802, 2164, 1880, 1872, 1829, 1854, 1806, 1883, 2075,
       1863, 1855, 2042, 1919, 1861, 1911, 2150, 2255, 1824, 1905, 2122,
       1909, 2176, 2136, 1860, 1873, 1760, 1828, 2279, 1869, 1838, 1888,
       2219, 2098, 1937, 1841, 2249, 1810, 2096, 1940, 1807, 1811, 1850,
       1895, 1990, 1856, 1879, 2063, 2191, 1902, 1827, 2109, 2204, 2012,
       2086, 1865, 2054, 1773, 1805, 2129, 1916, 1834, 2068, 2116, 1930,
       1912, 2170, 2239, 1878, 1836, 1840, 2112, 1842, 2058, 1814, 2177,
       1764, 1936, 2034, 1819, 1917, 1767, 1830, 18

In [4]:
cvt = pd.read_csv("D:\SummerResearch\data\covertype\covertype_train.csv")

In [5]:
cvt.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Soil_Type1',
       'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5', 'Soil_Type6',
       'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11',
       'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type15',
       'Soil_Type16', 'Soil_Type17', 'Soil_Type18', 'Soil_Type19',
       'Soil_Type20', 'Soil_Type21', 'Soil_Type22', 'Soil_Type23',
       'Soil_Type24', 'Soil_Type25', 'Soil_Type26', 'Soil_Type27',
       'Soil_Type28', 'Soil_Type29', 'Soil_Type30', 'Soil_Type31',
       'Soil_Type32', 'Soil_Type33', 'Soil_Type34', 'Soil_Type35',
       'Soil_Type36', 'Soil_Type37', 'Soil_Type38', 'Soil_Type39',
       'Soil_Type40', 'Wilderness_Area2', 'Wilderness_Area3',
       'Wilderness_Area4